### PR TITLE
Needs checking if code is correct - Replaced a rusty car with an Ifrit

### PR DESCRIPTION
**Pull request by ST6Daniel**
(BP player request, all BP players will like this car) but please check if the path to the ArmA 3 ifrit (and some rusty texture) is correct.

### CODE REVIEW

**Comment by BOPMatt** [comment]
Last time I checked I was a BP player ... and I don't like this vehicle - at least not forBP.
Seriously now, there is a couple of things wrong with this imho:

- Putting up something for a pull request without any prior testing whatsoever (and if you had done any you wouldn't need to ask if the path is correct etc.) is just irresponsible and not the way a project like this works. That being said, there is always the possibility of bugs/errors. We're all human, doing this in our spare time and without a huge QA-team backing us up.
- That change, if done correctly, would have a massive impact in terms of gameplay balancing for the entire BP-ecosystem. To be honest, adding such a vehicle as a replacement for a low-tier vehicle with a somewhat higher spawn chance would make the mod feel more like Exile or Epoch. I just don't see it fitting anywhere into the BP-theme at all - and that's regardless of the spawn chance.
- I'm aware that not all changes we've put up for merging are to everyone's liking. That's why we (being Dilli and me) either go for making things configurable or at least weigh the impact to the mod as a whole trying to preserve the theme/atmosphere/spirit.

But, hey, I could be wrong with my assessment ... wouldn't be the first time. ;)

**Comment by ST6Daniel** [comment]
Well I'm sorry I don't have the money to buy an ArmA 3 server to test my own BP build... :/ Also on another note I think it's bad enough atm that most players play large and boring Altis instead of Tanoa for example (if there were a BP Tanoa server even online).

**Comment by MorphineBP** [comment]
Dude are you a troll ??
- You can launch a BP server on your own computer and play on it. No need to pay anything.
- There is at least one Tanoa server, I'm playing on it (SWESOC).
Can you stop posting BS please ?! You're 100% wrong all the time.

**Comment by ST6Daniel** [comment]
Lol ok also right I had this closed good you can un-close it xD now just need to figure out how to launch BP in "singleplayer" (will do that on my own)

**Pull request closed without merging**
