### PR TITLE
Improved zombies & ballistics

### PR DESCRIPTION
**Pull request by malcain**
Zombie runspeed and armor increase. 
- Zeds can only be one-shot in the head. Body and other parts can take some damage before zed dies.
- Runspeed increase. Big boost on zed sprint. Walk speed was increased a bit in order for animation&gameplay to look more natural. All values were tested.

Slow and easy killable zombies were providing no threat and gameplay-wise were useless. 
Cities/Military areas shall provide a threat always, even if no players are around. 
Stronger zombies help to make it happen.

### CODE REVIEW

**Comment by deathlyrage** [comment]
Can't merge these changes unless there is a server option or something to disable it. These changes could break a lot of things.

**Comment by malcain** [comment]
Reverted all changes in "ModSource/breakingpoint_code/Configs/CfgVehicles.hpp".
New changes can no longer affect anything but zombies, nothing except zombies can be break (which is highly unlikely).
Have been tested dozen times.

**Comment by malcain** [comment]
Added Ballistic changes for SVDK, M-25, .300 Winmag & .338 Lapua.

_Sources&Maths on ballistics:_

**9.3x64mm Brenneke source:**
_Velocity:_
"The Brenneke achieves 3000fps with a 225 to 232 grain bullet and around 2500fps with a 293 to 300 grain bullet." 
2500fps = 762 m/s
InitSpeed and TypicalSpeed parameters were increased accordingly to that information.
Source: https://www.ballisticstudies.com/Knowledgebase/9.3x64+Brenneke.html

_Wiki sources on bullet damage(energy):_
~ x1.68 times higher bullet energy than 7.62x51 NATO (5.913J vs ~3.506J) ingame (19.69*1.68 = 33.07)
~ x1.93 times lower bullet energy than .408 Cheyenne Tactical (5.913J vs 11.352J) ingame (59/1.93 = 30.57)
Hit parameter was increased accordingly to that information, new Hit = **31.82**

Caliber(and armor pierce effectiveness) is roughly 1.1 times higher than .338 Lapua Magnum at close ranges. 
Caliber parameter increased accordingly to **2.910000**

_To keep the bullet drop, energy drop and accuracy the same(9.3x64 is only effective for up to ~400 meters): air friction was increased._


**.300 Winchester Magnum comparing to 7.62x51 ammo:** 
_Sources:_ 
http://www.snipercentral.com/300-winchester-magnum/
http://www.snipercentral.com/308-winchester-7-62x51mm-nato/ 
http://www.snipercentral.com/308-winchester-7-62x51mm-nato/
https://www.swggun.org/300-win-mag-vs-308

Mk248Mod0 (A191) = 190gr Sierra Match King at 2900fps
Mk248Mod1 = 220gr Sierra Match King at 2830fps

Energy (Muzzle: A191 – 3547Ft-Lbs., Mk248Mod1 – 3912)
Mk248Mod0 	3134 	2760 	2423 	2118 	1845 	1598 	1378 	1183 	1013 	867 	744 	644
Mk248Mod1 	3519 	3159 	2828 	2525 	2249 	1996 	1766 	1557 	1368 	1199 	1050 	921

_Muzzle energy is **~1.33** higher for .300 Winchester Magnum & **~1.47** higher for .300 Mk248Mod1 bullets._ 
_Hit parameter was increased accordingly to that information._

**Comment by malcain** [comment]
All changes have been tested between players on a dedicated test server and are working like intended.

**Pull request closed without merging**
